-- Create Orders table
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_ref TEXT UNIQUE NOT NULL,
    customer_name TEXT NOT NULL,
    customer_email TEXT NOT NULL,
    shipping_address TEXT NOT NULL,
    total_amount NUMERIC NOT NULL,
    status TEXT DEFAULT 'paid', -- 'pending', 'paid', 'completed', 'cancelled'
    items JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for orders
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public insert of orders" ON public.orders
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow admin read/write of orders" ON public.orders
    FOR ALL USING (auth.role() = 'authenticated');

-- Create Event Registrations table
CREATE TABLE IF NOT EXISTS public.registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES public.events(id) ON DELETE CASCADE NOT NULL,
    full_name TEXT NOT NULL,
    email TEXT NOT NULL,
    age TEXT NOT NULL,
    phone TEXT NOT NULL,
    emergency_contact_name TEXT NOT NULL,
    emergency_contact_phone TEXT NOT NULL,
    dietary_restrictions TEXT,
    medical_info TEXT,
    status TEXT DEFAULT 'registered', -- 'registered', 'cancelled', 'attended'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for registrations
ALTER TABLE public.registrations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public insert of registrations" ON public.registrations
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow admin read/write of registrations" ON public.registrations
    FOR ALL USING (auth.role() = 'authenticated');
