-- Create Product Inventory Table
CREATE TABLE IF NOT EXISTS public.product_inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.store_products(id) ON DELETE CASCADE NOT NULL,
    size TEXT NOT NULL, -- e.g., 'S', 'M', 'L', 'XL', 'OS'
    stock INT DEFAULT 0 NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(product_id, size)
);

-- Enable RLS for inventory
ALTER TABLE public.product_inventory ENABLE ROW LEVEL SECURITY;

-- Create Policies
CREATE POLICY "Allow public read of inventory" ON public.product_inventory
    FOR SELECT USING (true);

CREATE POLICY "Allow admin edit of inventory" ON public.product_inventory
    FOR ALL USING (auth.role() = 'authenticated');
