-- Create Admin Profiles table
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users ON DELETE CASCADE,
    email TEXT UNIQUE NOT NULL,
    full_name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security for profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read of profiles" ON public.profiles
    FOR SELECT USING (true);

CREATE POLICY "Allow users to update own profile" ON public.profiles
    FOR UPDATE USING (auth.uid() = id);

-- Create Site Settings table (for general configs like hero title, layout constants)
CREATE TABLE IF NOT EXISTS public.site_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,
    value JSONB NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read of settings" ON public.site_settings
    FOR SELECT USING (true);

CREATE POLICY "Allow admin edit of settings" ON public.site_settings
    FOR ALL USING (auth.role() = 'authenticated');

-- Create Events / Gatherings table
CREATE TABLE IF NOT EXISTS public.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    category TEXT, -- 'retreat', 'camp', 'talk', 'trip', 'online', etc.
    age_range TEXT,
    start_date DATE,
    end_date DATE,
    location TEXT,
    price TEXT,
    status TEXT DEFAULT 'draft', -- 'draft', 'open', 'coming-soon', 'closed', 'sold-out', 'past'
    short_description TEXT,
    long_description TEXT,
    registration_url TEXT,
    payment_url TEXT,
    external_checkout_url TEXT,
    liability_form_url TEXT,
    application_url TEXT,
    scholarship_contact_url TEXT,
    hero_image TEXT,
    gallery_images TEXT[] DEFAULT '{}',
    featured_on_homepage BOOLEAN DEFAULT false,
    published BOOLEAN DEFAULT false,
    seo_title TEXT,
    seo_description TEXT,
    stripe_price_id TEXT,
    stripe_product_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read of published events" ON public.events
    FOR SELECT USING (published = true OR auth.role() = 'authenticated');

CREATE POLICY "Allow admin write of events" ON public.events
    FOR ALL USING (auth.role() = 'authenticated');

-- Create Event Highlights table
CREATE TABLE IF NOT EXISTS public.event_highlights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES public.events(id) ON DELETE CASCADE NOT NULL,
    highlight TEXT NOT NULL
);

ALTER TABLE public.event_highlights ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read of event highlights" ON public.event_highlights
    FOR SELECT USING (true);

CREATE POLICY "Allow admin write of event highlights" ON public.event_highlights
    FOR ALL USING (auth.role() = 'authenticated');

-- Create Event Schedule table
CREATE TABLE IF NOT EXISTS public.event_schedule_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES public.events(id) ON DELETE CASCADE NOT NULL,
    time_label TEXT, -- e.g. "8:00 AM", "Evening"
    title TEXT NOT NULL,
    description TEXT
);

ALTER TABLE public.event_schedule_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read of schedule" ON public.event_schedule_items
    FOR SELECT USING (true);

CREATE POLICY "Allow admin write of schedule" ON public.event_schedule_items
    FOR ALL USING (auth.role() = 'authenticated');

-- Create Event FAQs table
CREATE TABLE IF NOT EXISTS public.event_faqs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES public.events(id) ON DELETE CASCADE NOT NULL,
    question TEXT NOT NULL,
    answer TEXT NOT NULL
);

ALTER TABLE public.event_faqs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read of faqs" ON public.event_faqs
    FOR SELECT USING (true);

CREATE POLICY "Allow admin write of faqs" ON public.event_faqs
    FOR ALL USING (auth.role() = 'authenticated');

-- Create Event People (Organizers/Counselors) table
CREATE TABLE IF NOT EXISTS public.event_people (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES public.events(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    role TEXT,
    bio TEXT,
    image_url TEXT
);

ALTER TABLE public.event_people ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read of event hosts" ON public.event_people
    FOR SELECT USING (true);

CREATE POLICY "Allow admin write of event hosts" ON public.event_people
    FOR ALL USING (auth.role() = 'authenticated');

-- Create Resources table
CREATE TABLE IF NOT EXISTS public.resources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT,
    description TEXT,
    external_url TEXT,
    uploaded_file_url TEXT,
    published BOOLEAN DEFAULT true,
    sort_order INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.resources ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read of resources" ON public.resources
    FOR SELECT USING (published = true OR auth.role() = 'authenticated');

CREATE POLICY "Allow admin write of resources" ON public.resources
    FOR ALL USING (auth.role() = 'authenticated');

-- Create Store Products table
CREATE TABLE IF NOT EXISTS public.store_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_title TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    description TEXT,
    image TEXT,
    price TEXT,
    status TEXT DEFAULT 'available', -- 'available', 'unavailable', 'sold-out'
    external_checkout_url TEXT,
    external_product_url TEXT,
    stripe_price_id TEXT,
    stripe_product_id TEXT,
    featured BOOLEAN DEFAULT false,
    published BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.store_products ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read of products" ON public.store_products
    FOR SELECT USING (published = true OR auth.role() = 'authenticated');

CREATE POLICY "Allow admin write of products" ON public.store_products
    FOR ALL USING (auth.role() = 'authenticated');

-- Create Newsletter Subscribers table
CREATE TABLE IF NOT EXISTS public.newsletter_subscribers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    subscribed_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.newsletter_subscribers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public insert of newsletter" ON public.newsletter_subscribers
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow admin read/write of newsletter" ON public.newsletter_subscribers
    FOR ALL USING (auth.role() = 'authenticated');

-- Create Contact Messages table
CREATE TABLE IF NOT EXISTS public.contact_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    email TEXT NOT NULL,
    message TEXT NOT NULL,
    reviewed BOOLEAN DEFAULT false,
    submitted_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public insert of contact messages" ON public.contact_messages
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow admin read/write of contact messages" ON public.contact_messages
    FOR ALL USING (auth.role() = 'authenticated');

-- Create trigger to automatically create profiles for new auth users
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name)
  VALUES (new.id, new.email, new.raw_user_meta_data->>'full_name');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
